services:
  - type: web
    name: energy-news-bot-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: PORT
        value: 10000
